import { Palette } from "std-widgets.slint";
export component MyIconButton inherits Rectangle {
    in property <image> clicked_icon_path;
    in property <image> hover_icon_path;
    in property <image> normal_icon_path;
    in property <length> icon_height: 14px;
    in property <length> icon_width: 14px;
    in-out property <string> state: "normal";
    in property <bool> selected: false;  // 新增：选中状态
    callback icon_clicked();
    in-out property <color> icon_color;
    in-out property <bool> icon_clip: true;

    height: icon_height;
    width: icon_width;
    border-radius: self.height / 2;
    clip: icon_clip;

    ta := TouchArea {
        width: parent.width;
        height: parent.height;
        ta_img := Image {
            height: root.height;
            width: root.width;
            source: selected?clicked_icon_path:root.normal_icon_path;
            colorize: root.icon_color;
        }

        clicked => {
            root.icon_clicked();
        }
    }

    states [
        hover when ta.has-hover && !ta.pressed: {
            ta_img.source: root.hover_icon_path;
            root.state: "button hover";
        }
        pressed when ta.pressed: {
            ta_img.source: root.clicked_icon_path;
            root.state: "button press";
        }
        hover_pressed when ta.has-hover && ta.pressed: {
            ta_img.source: root.clicked_icon_path;
            root.state: "button click";
        }
    ]
}
