import { HorizontalBox } from "std-widgets.slint";
import { MyIconButton } from "../components/my_icon_button.slint";

// 顶部工具栏
export component HeaderBar inherits Rectangle {
    height: 35px;
    width: 1600px;
    background: #353943;
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;

    traffic_light_area := Rectangle {
        VerticalLayout {
            alignment: center;
            HorizontalBox {
                padding-left: 12px;
                red_close := MyIconButton {
                    max-height: 14px;
                    normal_icon_path: @image-url("../../assets/macos-traffic-light-buttons/1-close-1-normal.svg");
                    hover_icon_path: @image-url("../../assets/macos-traffic-light-buttons/2-close-2-hover.svg");
                    clicked_icon_path: @image-url("../../assets/macos-traffic-light-buttons/2-close-3-press.svg");
                }

                yellow_minimal := MyIconButton {
                    normal_icon_path: @image-url("../../assets/macos-traffic-light-buttons/2-minimize-1-normal.svg");
                    hover_icon_path: @image-url("../../assets/macos-traffic-light-buttons/2-minimize-2-hover.svg");
                    clicked_icon_path: @image-url("../../assets/macos-traffic-light-buttons/2-close-3-press.svg");
                }

                green_max := MyIconButton {
                    normal_icon_path: @image-url("../../assets/macos-traffic-light-buttons/3-maximize-1-normal.svg");
                    hover_icon_path: @image-url("../../assets/macos-traffic-light-buttons/3-maximize-2-hover.svg");
                    clicked_icon_path: @image-url("../../assets/macos-traffic-light-buttons/3-maximize-3-press.svg");
                }
            }
        }
    }
}
