import { FooterBar } from "footer_bar/footer_bar.slint";
import { MainWindow } from "main_window/main_window.slint";

import { DragWindow,WindowStore } from "global.slint";
import { HeaderBar } from "header_bar/macos_header_bar.slint";
import { VerticalBox } from "std-widgets.slint";
export { DragWindow, WindowStore } from "global.slint";

export component APP inherits Window {
    callback drag_alias(length, length);
    in-out property <bool> is_dragging:false;
    min-width: 900px;
    min-height: 600px;
    background: transparent;
    no-frame: true;

    VerticalLayout {
        HeaderBar { }

        MainWindow { }

        FooterBar { }
    }
}
